export const REQUEST_BURGER_INGREDIENTS: "REQUEST_BURGER_INGREDIENTS" =
  "REQUEST_BURGER_INGREDIENTS";
export const SUCCESS_BURGER_INGREDIENTS: "SUCCESS_BURGER_INGREDIENTS" =
  "SUCCESS_BURGER_INGREDIENTS";
export const FAILED_BURGER_INGREDIENTS: "FAILED_BURGER_INGREDIENTS" =
  "FAILED_BURGER_INGREDIENTS";
export const CHANGE_TAB: "CHANGE_TAB" = "CHANGE_TAB";
export const SET_MODAL_ELEMENT: "SET_MODAL_ELEMENT" = "SET_MODAL_ELEMENT";

export const TOGGLE_MODAL: "TOGGLE_MODAL" = "TOGGLE_MODAL";
