export const ADD_ITEM: "ADD_ITEM" = "ADD_ITEM";
export const NEW_CART_ORDER: "NEW_CART_ORDER" = "NEW_CART_ORDER";
export const CLEAR_CART: "CLEAR_CART" = "CLEAR_CART";
export const DELETE_ITEM: "DELETE_ITEM" = "DELETE_ITEM";
export const SET_BUN: "SET_BUN" = "SET_BUN";

export const SEND_ORDER_REQUEST: "SEND_ORDER_REQUEST" = "SEND_ORDER_REQUEST";
export const SEND_ORDER_SUCCESS: "SEND_ORDER_SUCCESS" = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILED: "SEND_ORDER_FAILED" = "SEND_ORDER_FAILED";

export const TOGGLE_CONSTRUCTOR_MODAL: "TOGGLE_CONSTRUCTOR_MODAL" =
  "TOGGLE_CONSTRUCTOR_MODAL";
